### ISSUE TITLE
NetCDF files types

### ISSUE THREAD

**Issue by gutierrad** [Deltares/SFINCS#37]
Hi,
I have just joined a new team at UCSC that has run SFINCS for some time now.
I have been given a test case to check my recent SFINCS compilation and I have noticed that they used the bin output instead of the NetCDF output.
It turns out that for the size of this model (island, around 36M cells), the model complained about the NetCDF file when creating it and refused to continue.
I went into the code to find that currently, the NetCDF files created by SFINCS are NetCDF-3 type (that are limited in size).
I modified the code to try NetCDF-4 type files with and without compression and everything looks good.
I have also tried the generated NetCDF files with QUICKPLOT and they seem to work.

At this point, I have some questions:
- Did you explore NetCDF-4 files at any moment during the development?
- If you did, why did you stay with NetCDF-3?

We would like this to be implemented, so I could finish the implementation of the "Write NetCDF-4 output files" feature, but when I have reviewed the config file read procedure and seen how everything is implemented, some doubts have arisen that would probably be worth discussing about what to have as a parameter and what to have "hardcoded":
- Is it worth allowing the user to choose between NetCDF-3 and NetCDF-4 output files? (If there was a reason so as not to use NetCDF-4, this would be a must)
- I guess all of the .nc files generated by a given run should be one or the other.
- Is it worth letting the user choose whether to use compression or not? (I think so)
- Is it worth letting the user choose the deflate level? (I think so)
- Is it worth letting the user decide about some of the rest of the NetCDF-4 features, such as chunking (at the moment, I don't think so)

I have some other questions about how you would prefer some things to be implemented, but this could be discussed later once the functions to be implemented are decided.

Thank you very much,
David Gutiérrez-Barceló
UCSC

**Comment by roeldegoede** [comment]
Hi David, thanks for raising these questions and suggestions. The NetCDF libraries have always caused headaches on our side and as far as I'm aware, we did not consider switching to NetCDF-4 before. Since it seems that you have already something working, we would like to encourage you to push this in a separate branch and open a pull request! This makes it easy for us to review (and test) what you have so far. 

The options for compression and deflation seem like a good idea (for the more advanced users), as long as basic users don't have to worry about these (this is already solved by having good default values). If you want to further discuss this, maybe good to schedule a call?

**Comment by gutierrad** [comment]
Hi Roel,

Sure. I just wanted to align with you before going with the pull request.
The call is a good idea. Should I send an email to sfincs at deltares.nl?

D

**Comment by roeldegoede** [comment]
Hi David,

Yes, that would be great! Then we can follow up via e-mail.

Roel

**Comment by Leynse** [comment]
Dear David,

thanks for raising this issue and possible improvements!

I understand that you had a good call with my colleagues, but that there was a problem in committing the code with your pc.

Would it be possible for you to try this again?

Then we can potentially include it in our Q4 release.

Best,
Tim

**Comment by gutierrad** [comment]
Hi Tim,

Everything went fine.
Right after the call, my main development computer died and I have been
dealing with something else.
I will be back to Santa Cruz next week and will try to have a pull request
as soon as possible.
What is the deadline to include in the Q4 release?

Best,
David

**Comment by Leynse** [comment]
Hi David,

no rush! All help is greatly appreciated.

We will decide on including new features and their status somewhere mid-October, so there's time still.
And otherwise can always leave it in a branch for now and add it in the Q2 2024 release.

Curious to see your suggestions whenever it suits you!
Best, 
Tim

**Comment by gutierrad** [comment]
Hi Tim,

I have already sent a pull request.
Don't hesitate contacting for any comment.

Cheers,
David
