### ISSUE TITLE
The return code of the SFINCS model is always 0 even if the model fails

### ISSUE THREAD

**Issue by jensdebruijn** [Deltares/SFINCS#39]
SFINCS always gives a return code of 0, even if the model run failed (e.g., reached maximum depth of 100 m). If the return code would be 1 in such cases, this would help in checking whether the model successfully completed, for example when running the model using Python's subprocess.

**Comment by roeldegoede** [comment]
Hi Jens, thanks for bringing this up! This is something we didn't consider ourselves before, but since we also see the added value of it, we will have a look at this anytime soon. We'll keep you posted.

**Comment by Leynse** [comment]
Dear Jens, thanks for raising this issue!

I made a separate branch and started working on it. The easy fix of actually updating the internal error flag 'ierr' works, so that in sfincs.f90 we get that error code out of 'sfincs_update' subgroutine, and then the subroutine 'sfincs_finalize' is not called anymore. This error code should be available when you run SFINCS through BMI in Python. 
However, for running the windows exe which you do presumable, this is not the case yet, since the program still closes off normally (believe that gives the code = 0). Changing that requires some more work, will have to ask a colleague and might take some more time unfortunately.

Separate quick fix in your work flow is to write a few lines of code in Python, to search in 'sfincs_log.txt' output log-file for the words"Simulation stopped", and then give raise an error code/warning yourself

**Comment by jensdebruijn** [comment]
Thanks Tim! I will use your suggestion for now!
