### ISSUE TITLE
Compilation failed with gfortran due to unprocessed macro

### ISSUE THREAD

**Issue by jamal919** [Deltares/SFINCS#41]
Hi,

I started looking into SFINCS this afternoon, and tried to compile the main branch with gfortran 11.2 and gnu automake toolchain. It failed with unclassifiable statement error at -

https://github.com/Deltares/SFINCS/blob/b5d6b0793832a5335f5b8264ebf8f0b79b6106b7/source/src/quadtree.f90#L1

It appears that in ccfc3ccacd1659f1a2d23e88ad40069908ba79df the macro is added. gfortran does not auto pre-process files with *.f90 extension, hence it is failing to compile. Simple fix is to rename the src/quadtree.f90 to src/quadtree.F90.

**Comment by Leynse** [comment]
Hi Jamal,

thanks for letting us know.

I tried to already do this in recent commit 1058571, but I see that my change of .f90 to .F90 didn't came through.
Now fixed in a5136da.

Other question; for what application do you want to compile a linux build yourself?

So far others seem satisfied with using our Docker / Singularity solution (https://hub.docker.com/r/deltares/sfincs-cpu).

Best,
Tim

**Comment by Leynse** [comment]
Hi Peter,

great to hear.

Also same question to you (out of curiosity as product owner); for what type of application/use do you need a personal Linux build?
(we already provide windows executables and Docker linux builds (/possible to run on Singularity)).

Best,
Tim

**Comment by jamal919** [comment]
Hi @Leynse, 

Thanks for the fix. The docker solution is indeed very nice, which I tested side-by-side of compilation. But I personally prefer to compile in the cluster for a native build. I would like to test beforehand if there is a substantial gain from going to native build from a singularity container. I appreciate if you have any suggestion.

**Comment by Leynse** [comment]
@Peter9192 - oké great, curious to hear at some point how the grpc4bmi approach is different than the current BMI implementation we have with combined use of bmi-python (https://github.com/openearth/bmi-python) as we did some tests with so far

**Comment by Leynse** [comment]
@jamal919 Okay clear, we did try Singularity containers recently besides native linux builds and Docker containers, but I don't have any numbers for you how much the gain might be yet. Curious to hear about your experiences though!
In general we promote the Docker (or Singularity through Docker pull) use because for people with less experience in linux compiling than you 2, it's just easier to deal with.

**Comment by Peter9192** [comment]
> @Peter9192 - oké great, curious to hear at some point how the grpc4bmi approach is different than the current BMI implementation we have with combined use of bmi-python (https://github.com/openearth/bmi-python) as we did some tests with so far

With grpc4bmi, the model lives in a container, while the client lives outside it. Do you have a public code somewhere that illustrates how you call the sfincs-bmi functions with bmi-python? That might be helpful
